print("Hello I am ur chatbot my name is DOUGHNUT LORD")
print("What is ur name?")
name = input("")
print(f"hello {name}")
print("Before we start can i call u potato?")
potato = input ("")
print("idk ur potato from now on")
input ("So what brings u to ur SUPER SONIC CHATBOT?")
answer1 = input ("Would u like me to make u a personlized list on how i can help answer yes or no pls?")
if answer1 == "Yes" :
    print ("Let me ask u a few questions first") 
print ("Im sorry is there anything else I can help u with?")
print ("sry i have to speed this up a bit ur probably better off with chat gpt")
ok = input ("")
print ("oki bye now i lowkwy js did this for credit sry")
print ("$$$DOUNUT LORD SIGNING OFF$$$")
print ("```````````````````````")
print ("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print ("BEEEEEEEEEEEEEEEEEEEEEEEEEEPPPPPPPPP BEEP BEP BEP_____<3")